
---
- hosts: localhost
  tasks:

    - name: Save existing SSH Key as fact
      set_fact:
        cacheable: True
        secure_ip_display: "{{ test }}"
    - name: Print message
      debug:
        msg: This is the resolved value {{ secure_ip_display }} now
