
---
- hosts: localhost
  tasks:

    - name: Save existing SSH Key as fact
      set_fact:
        cacheable: True
        secure_ip_display: "{{ test }}"
    
    - name: Execute shell command
      shell: ibmcloud login --apikey "{{ test }}" -a test.cloud.ibm.com
      register: command_output

    - name: Print message
      debug:
        msg: This is the resolved value {{ secure_ip_display }} now

    - name: Print command output
      debug:
        msg: output is -  {{command_output.stdout}}
